package com.example.ui

import android.content.Context
import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.*
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.snapshots.SnapshotStateMap
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.rotate
import androidx.compose.ui.draw.scale
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.ResumeProfile
import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.sin

// Theme Specific Colors
val PrimaryPurple = Color(0xFF6366F1)
val SecondaryPink = Color(0xFFEC4899)
val AccentingEmerald = Color(0xFF10B981)
val AmbientWarning = Color(0xFFF59E0B)
val LightSlate = Color(0xFF64748B)

// Core Data Structures
data class RoadmapMilestone(
    val id: String,
    val title: String,
    val description: String,
    val extraTip: String = ""
)

data class CertificateGoal(
    val id: String,
    val title: String,
    val provider: String,
    val description: String
)

data class CapstoneProject(
    val id: String,
    val title: String,
    val overview: String,
    val defaultTasks: List<String>
)

/**
 * Robust structural parser utility for freeform text generated by Gemini to ensure premium segmented visual cards.
 */
object RoadmapParser {
    fun parseMilestones(rawText: String): List<RoadmapMilestone> {
        val result = mutableListOf<RoadmapMilestone>()
        val lines = rawText.split("\n")
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("[") && !it.startsWith("]") }

        var currentTitle = ""
        val detailBuilder = StringBuilder()

        for (line in lines) {
            val cleanLine = line
                .replace(Regex("^[-*•\\d+.]\\s*"), "") // strip lead bullet symbols
                .replace(Regex("[*#_]"), "")           // strip markdown emphasis symbols
                .trim()

            if (cleanLine.lowercase().startsWith("phase") || 
                cleanLine.lowercase().startsWith("step") || 
                cleanLine.lowercase().startsWith("week") || 
                cleanLine.lowercase().startsWith("milestone") || 
                (cleanLine.length < 50 && cleanLine.contains(Regex("^\\s*\\d+")))) {
                
                if (currentTitle.isNotBlank()) {
                    result.add(
                        RoadmapMilestone(
                            id = "milestone_${result.size}_${currentTitle.hashCode()}",
                            title = currentTitle,
                            description = detailBuilder.toString().trim()
                        )
                    )
                    detailBuilder.clear()
                }
                currentTitle = cleanLine
            } else {
                if (currentTitle.isBlank() && cleanLine.length > 5) {
                    currentTitle = "Milestone ${result.size + 1}: Goal Setting"
                }
                detailBuilder.append(cleanLine).append(" ")
            }
        }

        if (currentTitle.isNotBlank()) {
            result.add(
                RoadmapMilestone(
                    id = "milestone_${result.size}_${currentTitle.hashCode()}",
                    title = currentTitle,
                    description = detailBuilder.toString().trim()
                )
            )
        }

        // Fallback for empty parsing to ensure high fidelity
        if (result.isEmpty()) {
            val paragraphs = rawText.split("\n\n").filter { it.isNotBlank() }
            paragraphs.forEachIndexed { i, para ->
                val clean = para.replace(Regex("[*#_]"), "").trim()
                val head = if (clean.length > 40) clean.take(35) + "..." else clean
                result.add(
                    RoadmapMilestone(
                        id = "milestone_fallback_$i",
                        title = "Learning Phase ${i + 1}: $head",
                        description = clean
                    )
                )
            }
        }

        return result
    }

    fun parseCertificates(rawText: String): List<CertificateGoal> {
        val list = mutableListOf<CertificateGoal>()
        val lines = rawText.split("\n")
            .map { it.replace(Regex("[*#_]"), "").trim() }
            .filter { it.isNotBlank() && !it.startsWith("[") && !it.startsWith("]") }

        lines.forEachIndexed { idx, line ->
            val clean = line.replace(Regex("^[-*•\\d+.]\\s*"), "").trim()
            if (clean.length > 5) {
                val halves = clean.split(Regex("[-:]"), 2)
                val title = halves.firstOrNull()?.trim() ?: "Credential Program ${idx + 1}"
                val desc = halves.getOrNull(1)?.trim() ?: "Pre-arranged certified track mapping to industry roles."
                
                // Extract provider from title
                val provider = if (title.lowercase().contains("google")) "Google Cloud"
                              else if (title.lowercase().contains("aws")) "Amazon Web Services"
                              else if (title.lowercase().contains("microsoft") || title.lowercase().contains("azure")) "Microsoft"
                              else if (title.lowercase().contains("comptia")) "CompTIA"
                              else if (title.lowercase().contains("cisco")) "Cisco Systems"
                              else "Professional Authority"

                list.add(CertificateGoal(
                    id = "cert_${idx}_${title.hashCode()}",
                    title = title,
                    provider = provider,
                    description = desc
                ))
            }
        }

        if (list.isEmpty()) {
            list.add(CertificateGoal("cert_fb_1", "AWS Certified Solutions Architect", "AWS", "Validates technical expertise in designing and deploying scalable systems."))
            list.add(CertificateGoal("cert_fb_2", "Google Associate Cloud Engineer", "Google Cloud", "Demonstrates your capability to plan, configure, and secure system resources."))
        }
        return list.take(4)
    }

    fun parseProjects(rawText: String): List<CapstoneProject> {
        val list = mutableListOf<CapstoneProject>()
        val blocks = rawText.split(Regex("\n(?=\\s*\\d+\\.)|\n(?=\\s*[-*•]\\s*[A-Z])|\n\n"))
            .map { it.replace(Regex("[#*_]"), "").trim() }
            .filter { it.isNotBlank() && !it.startsWith("[") && !it.startsWith("]") }

        blocks.forEachIndexed { idx, block ->
            val lines = block.split("\n").filter { it.isNotBlank() }
            val mainLine = lines.firstOrNull()?.replace(Regex("^[-*•\\d+.]\\s*"), "")?.trim() ?: ""
            if (mainLine.length > 5) {
                val halves = mainLine.split(Regex("[-:]"), 2)
                val title = halves.firstOrNull()?.trim() ?: "Capstone Build Project ${idx + 1}"
                val overview = halves.getOrNull(1)?.trim() ?: lines.drop(1).joinToString(" ").trim()
                
                val dynamicTasks = listOf(
                    "Setup project architecture and scaffolding schema",
                    "Design database structure and localized ORM tables",
                    "Integrate API services and responsive state controller loops",
                    "Configure security checkpoints, validation logic, and unit tests",
                    "Construct interactive Jetpack Compose user frontend dashboard",
                    "Host code repositories and release live build artifact demonstration"
                )

                list.add(CapstoneProject(
                    id = "project_${idx}_${title.hashCode()}",
                    title = title,
                    overview = if (overview.isBlank()) "Complete software system designed to validate core skills relevant to recruiters." else overview,
                    defaultTasks = dynamicTasks
                ))
            }
        }

        if (list.isEmpty()) {
            list.add(CapstoneProject("proj_fb_1", "High-Throughput Analytics microservice", "Event-driven architecture streaming database optimization logs.", listOf("Schema Setup", "Ingest Pipelines", "Visual Dashboard")))
        }
        return list.take(3)
    }
}

@Composable
fun InteractiveRoadmapDashboard(
    profile: ResumeProfile,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    var activeSubTab by remember { mutableStateOf(0) } // 0: Timeline Tracker, 1: Skill Gap, 2: Credentials & Capstones
    
    // Parsed assets state
    val milestones = remember(profile.learningRoadmap) { RoadmapParser.parseMilestones(profile.learningRoadmap) }
    val certificates = remember(profile.certificationSuggestions) { RoadmapParser.parseCertificates(profile.certificationSuggestions) }
    val projects = remember(profile.projectSuggestions) { RoadmapParser.parseProjects(profile.projectSuggestions) }

    // local preferences persistent trackers
    val checkPrefs = remember(profile.id) { context.getSharedPreferences("roadmap_checks_${profile.id}", Context.MODE_PRIVATE) }
    
    // Milestones Checked Map
    val checkedMilestones = remember { mutableStateMapOf<String, Boolean>() }
    // Project Task checked state: key = project_id + "_" + task_index
    val checkedProjectTasks = remember { mutableStateMapOf<String, Boolean>() }
    // Interactive Skill toggle state (Self-Educating vs Missing)
    val selfEducatedSkills = remember { mutableStateMapOf<String, Boolean>() }

    // Hydrate persistent state on start
    LaunchedEffect(profile.id) {
        milestones.forEach { m ->
            checkedMilestones[m.id] = checkPrefs.getBoolean("milestone_${m.id}", false)
        }
        projects.forEach { p ->
            p.defaultTasks.forEachIndexed { idx, _ ->
                val k = "task_${p.id}_$idx"
                checkedProjectTasks[k] = checkPrefs.getBoolean(k, false)
            }
        }
        val customSkillsJson = checkPrefs.getString("self_educated_skills", "") ?: ""
        if (customSkillsJson.isNotEmpty()) {
            customSkillsJson.split(",").filter { it.isNotBlank() }.forEach {
                selfEducatedSkills[it] = true
            }
        }
    }

    val missingSkillsList = remember(profile.missingSkills) {
        profile.missingSkills.split(",").map { it.trim() }.filter { it.isNotEmpty() }
    }
    val acquiredSkillsList = remember(profile.parsedSkills) {
        profile.parsedSkills.split(",").map { it.trim() }.filter { it.isNotEmpty() }
    }

    // Dynamic Progress Calculations (Highly Interactive!)
    val completedMilestoneCount = checkedMilestones.values.count { it }
    val totalMilestones = milestones.size.coerceAtLeast(1)
    val milestoneProgressFrac = completedMilestoneCount.toFloat() / totalMilestones.toFloat()

    val totalProjectTasks = projects.flatMap { p -> p.defaultTasks.mapIndexed { idx, _ -> "task_${p.id}_$idx" } }
    val completedProjectTasks = totalProjectTasks.count { checkedProjectTasks[it] == true }
    val projectProgressFrac = if (totalProjectTasks.isNotEmpty()) completedProjectTasks.toFloat() / totalProjectTasks.size.toFloat() else 0f

    val educationalProgressPct = remember(milestoneProgressFrac, projectProgressFrac) {
        val avg = (milestoneProgressFrac * 0.7f) + (projectProgressFrac * 0.3f)
        (avg * 100f).coerceIn(0f, 100f)
    }

    // Render Container
    Column(
        modifier = modifier
            .fillMaxWidth()
            .testTag("interactive_career_dashboard")
    ) {
        // TOP GENERAL STATS PANEL: Mastery Index Dial & General Projections
        MasteryStatsHeaderPanel(
            profile = profile,
            educationalProgressPct = educationalProgressPct,
            missingSkillsSize = missingSkillsList.size,
            selfEducatedCount = selfEducatedSkills.size,
            acquiredSkillsSize = acquiredSkillsList.size
        )

        Spacer(modifier = Modifier.height(14.dp))

        // SEGMENTED SUB-TABS ROW FOR EXPANSION
        NavigationBarSubtabs(activeSubTab = activeSubTab, onTabSelect = { activeSubTab = it })

        Spacer(modifier = Modifier.height(14.dp))

        // ANIMATED TRANSITION BOARD CONTENT
        AnimatedContent(
            targetState = activeSubTab,
            transitionSpec = {
                slideInHorizontally { width -> if (targetState > initialState) width else -width } + fadeIn() togetherWith
                slideOutHorizontally { width -> if (targetState > initialState) -width else width } + fadeOut()
            },
            label = "tab_navigation"
        ) { tabIndex ->
            when (tabIndex) {
                0 -> {
                    // TAB 0: INTERACTIVE PROGRESS TIMELINE & STUDIES INTENSITY PLANNER
                    TimelineAndPlannerTab(
                        milestones = milestones,
                        checkedMilestones = checkedMilestones,
                        onMilestoneToggle = { id, checked ->
                            checkedMilestones[id] = checked
                            checkPrefs.edit().putBoolean("milestone_$id", checked).apply()
                        },
                        missingSkillsCount = missingSkillsList.size
                    )
                }
                1 -> {
                    // TAB 1: DYNAMIC SKILL GAP MATRIX (CLICK-TO-LEARN INTERACTIVE CLOUD)
                    SkillGapMatrixTab(
                        acquiredSkills = acquiredSkillsList,
                        missingSkills = missingSkillsList,
                        selfEducatedSkills = selfEducatedSkills,
                        onToggleSelfEducated = { skill ->
                            val current = selfEducatedSkills[skill] ?: false
                            val next = !current
                            if (next) {
                                selfEducatedSkills[skill] = true
                            } else {
                                selfEducatedSkills.remove(skill)
                            }
                            val updatedList = selfEducatedSkills.keys.joinToString(",")
                            checkPrefs.edit().putString("self_educated_skills", updatedList).apply()
                        }
                    )
                }
                2 -> {
                    // TAB 2: PORTFOLIOS, PROJECTS & VERIFIED CERTIFICATIONS TRACKER
                    PortfoliosAndCertificationsTab(
                        certificates = certificates,
                        projects = projects,
                        checkedTasks = checkedProjectTasks,
                        onTaskToggle = { idKey, checked ->
                            checkedProjectTasks[idKey] = checked
                            checkPrefs.edit().putBoolean(idKey, checked).apply()
                        }
                    )
                }
            }
        }
    }
}

@Composable
fun MasteryStatsHeaderPanel(
    profile: ResumeProfile,
    educationalProgressPct: Float,
    missingSkillsSize: Int,
    selfEducatedCount: Int,
    acquiredSkillsSize: Int
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .testTag("mastery_stats_header_panel"),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.2f)),
        shape = RoundedCornerShape(20.dp),
        border = BorderStroke(1.dp, MaterialTheme.colorScheme.onSurface.copy(alpha = 0.08f))
    ) {
        Row(
            modifier = Modifier.padding(16.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // ARC/DIAL RADIAL CHROME-LIKE PROGRESS SPEEDOMETER GAUGE
            Box(
                modifier = Modifier
                    .size(96.dp)
                    .testTag("completion_circular_gauge"),
                contentAlignment = Alignment.Center
            ) {
                val strokeColor = MaterialTheme.colorScheme.primary
                val backgroundColor = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.06f)
                val animatedProgress by animateFloatAsState(
                    targetValue = educationalProgressPct / 100f,
                    animationSpec = tween(1000, easing = EaseOutBack)
                )

                Canvas(modifier = Modifier.fillMaxSize()) {
                    val strokeWidth = 8.dp.toPx()
                    val sizeMin = size.minDimension - strokeWidth
                    val circularSize = Size(sizeMin, sizeMin)
                    val offset = strokeWidth / 2f

                    // Ground background path Arc (300 degree meter dial style)
                    drawArc(
                        color = backgroundColor,
                        startAngle = 120f,
                        sweepAngle = 300f,
                        useCenter = false,
                        topLeft = Offset(offset, offset),
                        size = circularSize,
                        style = Stroke(width = strokeWidth, cap = StrokeCap.Round)
                    )

                    // Active glow layer progression path
                    drawArc(
                        color = strokeColor.copy(alpha = 0.16f),
                        startAngle = 120f,
                        sweepAngle = 300f * animatedProgress,
                        useCenter = false,
                        topLeft = Offset(offset, offset),
                        size = circularSize,
                        style = Stroke(width = strokeWidth + 4.dp.toPx(), cap = StrokeCap.Round)
                    )

                    // Forward solid core arc
                    val brush = Brush.linearGradient(
                        colors = listOf(PrimaryPurple, SecondaryPink, AccentingEmerald)
                    )
                    drawArc(
                        brush = brush,
                        startAngle = 120f,
                        sweepAngle = 300f * animatedProgress,
                        useCenter = false,
                        topLeft = Offset(offset, offset),
                        size = circularSize,
                        style = Stroke(width = strokeWidth, cap = StrokeCap.Round)
                    )
                }

                // Internal Central status score text
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Text(
                        text = "${educationalProgressPct.toInt()}%",
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Black,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    Text(
                        text = "Prepared",
                        style = MaterialTheme.typography.labelSmall,
                        fontSize = 8.sp,
                        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f),
                        fontWeight = FontWeight.Bold
                    )
                }
            }

            // Text Details Header with instant dynamic breakdown analytics
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = "${profile.targetJobTitle} Architect",
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Black,
                    color = MaterialTheme.colorScheme.onSurface,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                )
                
                Text(
                    text = "A.I. Custom Training & CV Sync Syllabus",
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.primary,
                    fontWeight = FontWeight.SemiBold
                )

                Spacer(modifier = Modifier.height(6.dp))

                // Stats row
                Row(
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    StatBadge(label = "Acquired", count = acquiredSkillsSize + selfEducatedCount, color = AccentingEmerald)
                    StatBadge(label = "Gap Left", count = (missingSkillsSize - selfEducatedCount).coerceAtLeast(0), color = AmbientWarning)
                }
            }
        }
    }
}

@Composable
fun StatBadge(label: String, count: Int, color: Color) {
    Row(
        modifier = Modifier
            .clip(RoundedCornerShape(6.dp))
            .background(color.copy(alpha = 0.08f))
            .border(1.dp, color.copy(alpha = 0.15f), RoundedCornerShape(6.dp))
            .padding(horizontal = 6.dp, vertical = 2.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(4.dp)
    ) {
        Box(
            modifier = Modifier
                .size(6.dp)
                .clip(CircleShape)
                .background(color)
        )
        Text(
            text = "$label: $count",
            style = MaterialTheme.typography.labelSmall,
            fontWeight = FontWeight.Bold,
            color = color,
            fontSize = 9.sp
        )
    }
}

@Composable
fun NavigationBarSubtabs(
    activeSubTab: Int,
    onTabSelect: (Int) -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(12.dp))
            .background(MaterialTheme.colorScheme.onSurface.copy(alpha = 0.04f))
            .padding(4.dp),
        horizontalArrangement = Arrangement.spacedBy(4.dp)
    ) {
        val tabs = listOf(
            Triple(Icons.Default.DateRange, "Study Planner", 0),
            Triple(Icons.Default.Warning, "Skill Gap", 1),
            Triple(Icons.Default.Star, "Capstones", 2)
        )

        tabs.forEach { (icon, text, idx) ->
            val isSelected = activeSubTab == idx
            val containerColor by animateColorAsState(
                targetValue = if (isSelected) MaterialTheme.colorScheme.surface else Color.Transparent
            )
            val contentColor by animateColorAsState(
                targetValue = if (isSelected) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f)
            )

            Row(
                modifier = Modifier
                    .weight(1f)
                    .clip(RoundedCornerShape(10.dp))
                    .background(containerColor)
                    .clickable { onTabSelect(idx) }
                    .padding(vertical = 10.dp, horizontal = 4.dp)
                    .testTag("subtab_$idx"),
                horizontalArrangement = Arrangement.Center,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Icon(
                    imageVector = icon,
                    contentDescription = null,
                    tint = contentColor,
                    modifier = Modifier.size(16.dp)
                )
                Spacer(modifier = Modifier.width(6.dp))
                Text(
                    text = text,
                    style = MaterialTheme.typography.labelMedium,
                    fontWeight = FontWeight.Bold,
                    color = contentColor,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                )
            }
        }
    }
}

// =================== TAB COMPOSABLES ===================

@Composable
fun TimelineAndPlannerTab(
    milestones: List<RoadmapMilestone>,
    checkedMilestones: SnapshotStateMap<String, Boolean>,
    onMilestoneToggle: (String, Boolean) -> Unit,
    missingSkillsCount: Int
) {
    // HORIZON INTENSITY ROADMAP STUDY SLIDER PLANNER
    var weekIntensitySliderValue by remember { mutableStateOf(10f) } // default 10 hours/week

    val totalHoursNeeded = remember(missingSkillsCount) {
        (missingSkillsCount * 12).coerceAtLeast(30) // Estimate 12 hours of specialized training per major technical gap
    }

    val weeksRequiredProjected = remember(totalHoursNeeded, weekIntensitySliderValue) {
        kotlin.math.ceil(totalHoursNeeded.toFloat() / weekIntensitySliderValue.coerceAtLeast(1f)).toInt().coerceIn(1, 26)
    }

    Column(
        verticalArrangement = Arrangement.spacedBy(16.dp),
        modifier = Modifier.fillMaxWidth()
    ) {
        // Study Intensity Slider Card
        Card(
            modifier = Modifier.fillMaxWidth(),
            border = BorderStroke(1.dp, MaterialTheme.colorScheme.onSurface.copy(alpha = 0.05f)),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
        ) {
            Column(modifier = Modifier.padding(14.dp)) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Column {
                        Text(
                            text = "Interactive Weekly Study Speed Planner",
                            style = MaterialTheme.typography.bodyMedium,
                            fontWeight = FontWeight.Bold
                        )
                        Text(
                            text = "Tweak weekly dedication to visualize project completion milestones.",
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f)
                        )
                    }
                    Box(
                        modifier = Modifier
                            .clip(RoundedCornerShape(6.dp))
                            .background(MaterialTheme.colorScheme.primary.copy(alpha = 0.1f))
                            .padding(horizontal = 8.dp, vertical = 4.dp)
                    ) {
                        Text(
                            text = "${weekIntensitySliderValue.toInt()} Hours/wk",
                            style = MaterialTheme.typography.labelMedium,
                            fontWeight = FontWeight.Black,
                            color = MaterialTheme.colorScheme.primary
                        )
                    }
                }

                Spacer(modifier = Modifier.height(10.dp))

                Slider(
                    value = weekIntensitySliderValue,
                    onValueChange = { weekIntensitySliderValue = it },
                    valueRange = 2f..40f,
                    steps = 19,
                    modifier = Modifier.testTag("study_intensity_slider")
                )

                Divider(
                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.05f),
                    thickness = 0.8.dp,
                    modifier = Modifier.padding(vertical = 10.dp)
                )

                // STACKED TIME HORIZON BAR CHART GRAPH
                Text(
                    text = "Projected Study Time Horizon Graph",
                    style = MaterialTheme.typography.labelSmall,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f)
                )

                Spacer(modifier = Modifier.height(8.dp))

                // Chart Graphics showing 3 segments of roadmap progression and weeks required
                val theoryWeeks = (weeksRequiredProjected * 0.4f).coerceAtLeast(1f)
                val practiceWeeks = (weeksRequiredProjected * 0.4f).coerceAtLeast(1f)
                val testWeeks = (weeksRequiredProjected * 0.2f).coerceAtLeast(1f)
                val totalProportion = theoryWeeks + practiceWeeks + testWeeks

                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(36.dp)
                        .clip(RoundedCornerShape(8.dp))
                ) {
                    Box(
                        modifier = Modifier
                            .fillMaxHeight()
                            .weight(theoryWeeks / totalProportion)
                            .background(Brush.horizontalGradient(listOf(PrimaryPurple, PrimaryPurple.copy(alpha = 0.8f)))),
                        contentAlignment = Alignment.Center
                    ) {
                        Text(
                            text = "Theory: %.1fw".format(theoryWeeks),
                            style = MaterialTheme.typography.labelSmall,
                            fontWeight = FontWeight.Bold,
                            color = Color.White,
                            fontSize = 9.sp,
                            maxLines = 1
                        )
                    }
                    Box(
                        modifier = Modifier
                            .fillMaxHeight()
                            .weight(practiceWeeks / totalProportion)
                            .background(Brush.horizontalGradient(listOf(SecondaryPink, SecondaryPink.copy(alpha = 0.8f)))),
                        contentAlignment = Alignment.Center
                    ) {
                        Text(
                            text = "Projects: %.1fw".format(practiceWeeks),
                            style = MaterialTheme.typography.labelSmall,
                            fontWeight = FontWeight.Bold,
                            color = Color.White,
                            fontSize = 9.sp,
                            maxLines = 1
                        )
                    }
                    Box(
                        modifier = Modifier
                            .fillMaxHeight()
                            .weight(testWeeks / totalProportion)
                            .background(Brush.horizontalGradient(listOf(AccentingEmerald, AccentingEmerald.copy(alpha = 0.8f)))),
                        contentAlignment = Alignment.Center
                    ) {
                        Text(
                            text = "Mocking: %.1fw".format(testWeeks),
                            style = MaterialTheme.typography.labelSmall,
                            fontWeight = FontWeight.Bold,
                            color = Color.White,
                            fontSize = 9.sp,
                            maxLines = 1
                        )
                    }
                }

                Spacer(modifier = Modifier.height(8.dp))

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Text(
                        text = "Total Syllabus Work: $totalHoursNeeded technical study Hrs",
                        style = MaterialTheme.typography.labelSmall,
                        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f)
                    )
                    Text(
                        text = "Duration: ≈ $weeksRequiredProjected Training Weeks",
                        style = MaterialTheme.typography.labelSmall,
                        fontWeight = FontWeight.Black,
                        color = MaterialTheme.colorScheme.primary
                    )
                }
            }
        }

        // MILESTONES PROGRESS TRACKER TIMELINE LIST
        Text(
            text = "Interactive Timeline Milestone Roadmap",
            style = MaterialTheme.typography.bodyMedium,
            fontWeight = FontWeight.Black,
            color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.7f)
        )

        Column(
            modifier = Modifier.fillMaxWidth()
        ) {
            milestones.forEachIndexed { index, m ->
                val isChecked = checkedMilestones[m.id] ?: false

                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .animateContentSize(),
                    horizontalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    // LEFT GRAPHICAL TIMELINE CONNECTOR NODES
                    Column(
                        horizontalAlignment = Alignment.CenterHorizontally,
                        modifier = Modifier.width(24.dp)
                    ) {
                        // Node Circle Dot
                        Box(
                            modifier = Modifier
                                .size(24.dp)
                                .clip(CircleShape)
                                .background(
                                    if (isChecked) AccentingEmerald
                                    else MaterialTheme.colorScheme.onSurface.copy(alpha = 0.08f)
                                )
                                .border(
                                    1.5.dp,
                                    if (isChecked) Color.Transparent else MaterialTheme.colorScheme.onSurface.copy(alpha = 0.15f),
                                    CircleShape
                                ),
                            contentAlignment = Alignment.Center
                        ) {
                            if (isChecked) {
                                Icon(
                                    imageVector = Icons.Default.Check,
                                    contentDescription = "Completed Milestone",
                                    tint = Color.White,
                                    modifier = Modifier.size(14.dp)
                                )
                            } else {
                                Text(
                                    text = "${index + 1}",
                                    style = MaterialTheme.typography.labelSmall,
                                    fontWeight = FontWeight.Black,
                                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f)
                                )
                            }
                        }

                        // Vertical Connector line spanning towards next item
                        if (index < milestones.size - 1) {
                            Box(
                                modifier = Modifier
                                    .width(2.dp)
                                    .height(72.dp)
                                    .background(
                                        if (isChecked) AccentingEmerald.copy(alpha = 0.4f)
                                        else MaterialTheme.colorScheme.onSurface.copy(alpha = 0.06f)
                                    )
                            )
                        }
                    }

                    // RIGHT ACTION COGNITIVE CARD
                    Card(
                        modifier = Modifier
                            .weight(1f)
                            .padding(bottom = 14.dp)
                            .testTag("milestone_card_$index")
                            .clickable { onMilestoneToggle(m.id, !isChecked) },
                        border = BorderStroke(
                            1.dp,
                            if (isChecked) AccentingEmerald.copy(alpha = 0.25f)
                            else MaterialTheme.colorScheme.onSurface.copy(alpha = 0.05f)
                        ),
                        colors = CardDefaults.cardColors(
                            containerColor = if (isChecked) AccentingEmerald.copy(alpha = 0.02f)
                            else MaterialTheme.colorScheme.surface
                        )
                    ) {
                        Row(
                            modifier = Modifier.padding(12.dp),
                            verticalAlignment = Alignment.Top,
                            horizontalArrangement = Arrangement.spacedBy(10.dp)
                        ) {
                            Checkbox(
                                checked = isChecked,
                                onCheckedChange = { onMilestoneToggle(m.id, it) },
                                modifier = Modifier.scale(0.85f).testTag("milestone_checkbox_$index"),
                                colors = CheckboxDefaults.colors(
                                    checkedColor = AccentingEmerald,
                                    checkmarkColor = Color.White
                                )
                            )

                            Column(modifier = Modifier.weight(1f)) {
                                Text(
                                    text = m.title,
                                    style = MaterialTheme.typography.bodyMedium,
                                    fontWeight = FontWeight.Black,
                                    color = if (isChecked) AccentingEmerald else MaterialTheme.colorScheme.onSurface
                                )
                                Spacer(modifier = Modifier.height(4.dp))
                                Text(
                                    text = m.description,
                                    style = MaterialTheme.typography.labelMedium,
                                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f),
                                    lineHeight = 14.sp
                                )
                            }
                        }
                    }
                }
            }
        }
    }
}

@Composable
fun SkillGapMatrixTab(
    acquiredSkills: List<String>,
    missingSkills: List<String>,
    selfEducatedSkills: SnapshotStateMap<String, Boolean>,
    onToggleSelfEducated: (String) -> Unit
) {
    Column(
        verticalArrangement = Arrangement.spacedBy(14.dp),
        modifier = Modifier.fillMaxWidth()
    ) {
        // Skill Coverage Circular Ring Segment
        Card(
            modifier = Modifier.fillMaxWidth(),
            border = BorderStroke(1.dp, MaterialTheme.colorScheme.onSurface.copy(alpha = 0.05f)),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
        ) {
            Row(
                modifier = Modifier.padding(14.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                Box(
                    modifier = Modifier.size(64.dp),
                    contentAlignment = Alignment.Center
                ) {
                    val activeCount = acquiredSkills.size + selfEducatedSkills.size
                    val totalSkills = (acquiredSkills.size + missingSkills.size).coerceAtLeast(1)
                    val coverageFrac = activeCount.toFloat() / totalSkills.toFloat()

                    val ringBgColor = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.04f)
                    Canvas(modifier = Modifier.fillMaxSize()) {
                        drawCircle(
                            color = ringBgColor,
                            style = Stroke(width = 6.dp.toPx())
                        )
                        drawArc(
                            color = AccentingEmerald,
                            startAngle = -90f,
                            sweepAngle = 360f * coverageFrac,
                            useCenter = false,
                            style = Stroke(width = 6.dp.toPx(), cap = StrokeCap.Round)
                        )
                    }

                    Text(
                        text = "%.0f%%".format(coverageFrac * 100),
                        style = MaterialTheme.typography.labelLarge,
                        fontWeight = FontWeight.Black,
                        color = AccentingEmerald
                    )
                }

                Column {
                    Text(
                        text = "Dynamic Skills Checklist Coverage",
                        style = MaterialTheme.typography.bodyMedium,
                        fontWeight = FontWeight.Bold
                    )
                    Text(
                        text = "Tap orange skills to mark them as 'Self-Educator acquired' to instantly sync gaps and update readiness metrics.",
                        style = MaterialTheme.typography.labelSmall,
                        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f),
                        lineHeight = 12.sp
                    )
                }
            }
        }

        // Skills We Already Have Cloud List
        Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                Icon(Icons.Default.Check, contentDescription = null, tint = AccentingEmerald, modifier = Modifier.size(16.dp))
                Text(
                    text = "Acquired Skills Identified on Resume (${acquiredSkills.size})",
                    style = MaterialTheme.typography.labelMedium,
                    fontWeight = FontWeight.Bold,
                    color = AccentingEmerald
                )
            }
            FlowRowLayout(spacing = 6.dp) {
                acquiredSkills.forEach { s ->
                    Box(
                        modifier = Modifier
                            .clip(RoundedCornerShape(8.dp))
                            .background(AccentingEmerald.copy(alpha = 0.06f))
                            .border(1.dp, AccentingEmerald.copy(alpha = 0.15f), RoundedCornerShape(8.dp))
                            .padding(horizontal = 8.dp, vertical = 4.dp)
                    ) {
                        Text(
                            text = s,
                            style = MaterialTheme.typography.labelSmall,
                            fontWeight = FontWeight.Bold,
                            color = AccentingEmerald
                        )
                    }
                }
            }
        }

        // Gaps & Interactivity Cloud Matrix List
        Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                Icon(Icons.Default.Warning, contentDescription = null, tint = AmbientWarning, modifier = Modifier.size(16.dp))
                Text(
                    text = "Critical Technical Gaps Missing from CV (${missingSkills.size})",
                    style = MaterialTheme.typography.labelMedium,
                    fontWeight = FontWeight.Bold,
                    color = AmbientWarning
                )
            }
            
            Text(
                text = "Interactive: Click any gap chip below to toggle completion as you study.",
                style = MaterialTheme.typography.labelSmall,
                color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.4f)
            )

            FlowRowLayout(spacing = 6.dp) {
                missingSkills.forEach { gap ->
                    val isToggled = selfEducatedSkills[gap] ?: false

                    val brush = if (isToggled) {
                        Brush.linearGradient(listOf(AccentingEmerald, AccentingEmerald.copy(alpha = 0.7f)))
                    } else {
                        Brush.linearGradient(listOf(AmbientWarning.copy(alpha = 0.1f), AmbientWarning.copy(alpha = 0.05f)))
                    }

                    Row(
                        modifier = Modifier
                            .clip(RoundedCornerShape(8.dp))
                            .background(if (isToggled) Color.Transparent else Color.Companion.Transparent)
                            .background(brush)
                            .border(
                                width = 1.dp,
                                color = if (isToggled) AccentingEmerald.copy(alpha = 0.3f) else AmbientWarning.copy(alpha = 0.25f),
                                shape = RoundedCornerShape(8.dp)
                            )
                            .clickable { onToggleSelfEducated(gap) }
                            .padding(horizontal = 10.dp, vertical = 6.dp)
                            .testTag("skill_gap_chip_${gap}"),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(6.dp)
                    ) {
                        Icon(
                            imageVector = if (isToggled) Icons.Default.CheckCircle else Icons.Default.Add,
                            contentDescription = null,
                            tint = if (isToggled) Color.White else AmbientWarning,
                            modifier = Modifier.size(12.dp)
                        )
                        Text(
                            text = gap,
                            style = MaterialTheme.typography.labelSmall,
                            fontWeight = FontWeight.Black,
                            color = if (isToggled) Color.White else AmbientWarning
                        )
                    }
                }
            }
        }
    }
}

@Composable
fun PortfoliosAndCertificationsTab(
    certificates: List<CertificateGoal>,
    projects: List<CapstoneProject>,
    checkedTasks: SnapshotStateMap<String, Boolean>,
    onTaskToggle: (String, Boolean) -> Unit
) {
    Column(
        verticalArrangement = Arrangement.spacedBy(16.dp),
        modifier = Modifier.fillMaxWidth()
    ) {
        // Industry Credentials Sections
        Text(
            text = "Strategic Verification Credentials",
            style = MaterialTheme.typography.bodyMedium,
            fontWeight = FontWeight.Black,
            color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.7f)
        )

        Row(
            modifier = Modifier.horizontalScroll(rememberScrollState()),
            horizontalArrangement = Arrangement.spacedBy(10.dp)
        ) {
            certificates.forEachIndexed { i, cert ->
                Card(
                    modifier = Modifier
                        .width(220.dp)
                        .testTag("verification_cert_card_$i"),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                    border = BorderStroke(1.dp, MaterialTheme.colorScheme.onSurface.copy(alpha = 0.06f))
                ) {
                    Column(modifier = Modifier.padding(12.dp)) {
                        Row(
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically,
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Box(
                                modifier = Modifier
                                    .clip(RoundedCornerShape(6.dp))
                                    .background(MaterialTheme.colorScheme.primary.copy(alpha = 0.08f))
                                    .padding(horizontal = 6.dp, vertical = 2.dp)
                            ) {
                                Text(
                                    text = cert.provider,
                                    style = MaterialTheme.typography.labelSmall,
                                    color = MaterialTheme.colorScheme.primary,
                                    fontWeight = FontWeight.ExtraBold,
                                    fontSize = 8.sp
                                )
                            }

                            Icon(
                                imageVector = Icons.Default.Star,
                                contentDescription = null,
                                tint = AmbientWarning,
                                modifier = Modifier.size(14.dp)
                            )
                        }

                        Spacer(modifier = Modifier.height(8.dp))

                        Text(
                            text = cert.title,
                            style = MaterialTheme.typography.labelLarge,
                            fontWeight = FontWeight.Black,
                            color = MaterialTheme.colorScheme.onSurface,
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis
                        )
                        Spacer(modifier = Modifier.height(4.dp))
                        Text(
                            text = cert.description,
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f),
                            lineHeight = 12.sp,
                            maxLines = 3,
                            overflow = TextOverflow.Ellipsis
                        )
                    }
                }
            }
        }

        Divider(color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.05f), thickness = 0.8.dp)

        // Custom capstone Projects sections
        Text(
            text = "Active Capstone Portfolios Checklist Builder",
            style = MaterialTheme.typography.bodyMedium,
            fontWeight = FontWeight.Black,
            color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.7f)
        )

        projects.forEachIndexed { pIdx, proj ->
            var expandedProjectIndexState by remember { mutableStateOf(false) }

            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .animateContentSize()
                    .testTag("capstone_project_card_$pIdx"),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                border = BorderStroke(1.dp, MaterialTheme.colorScheme.onSurface.copy(alpha = 0.06f))
            ) {
                Column(modifier = Modifier.padding(14.dp)) {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clickable { expandedProjectIndexState = !expandedProjectIndexState },
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Column(modifier = Modifier.weight(1f)) {
                            Text(
                                text = proj.title,
                                style = MaterialTheme.typography.bodyMedium,
                                fontWeight = FontWeight.Black,
                                color = MaterialTheme.colorScheme.primary
                            )
                            Spacer(modifier = Modifier.height(2.dp))
                            Text(
                                text = proj.overview,
                                style = MaterialTheme.typography.labelSmall,
                                color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f),
                                maxLines = if (expandedProjectIndexState) 10 else 2,
                                overflow = TextOverflow.Ellipsis
                            )
                        }

                        IconButton(onClick = { expandedProjectIndexState = !expandedProjectIndexState }) {
                            Icon(
                                imageVector = if (expandedProjectIndexState) Icons.Default.KeyboardArrowUp else Icons.Default.KeyboardArrowDown,
                                contentDescription = null,
                                tint = MaterialTheme.colorScheme.primary
                            )
                        }
                    }

                    if (expandedProjectIndexState) {
                        Divider(
                            color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.05f),
                            thickness = 1.dp,
                            modifier = Modifier.padding(vertical = 10.dp)
                        )

                        Text(
                            text = "Project Scaffolds Checklist Tasks:",
                            style = MaterialTheme.typography.labelSmall,
                            fontWeight = FontWeight.Bold,
                            color = MaterialTheme.colorScheme.onSurface
                        )

                        Spacer(modifier = Modifier.height(8.dp))

                        proj.defaultTasks.forEachIndexed { tIdx, task ->
                            val keys = "task_${proj.id}_$tIdx"
                            val isChecked = checkedTasks[keys] ?: false

                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .clickable { onTaskToggle(keys, !isChecked) }
                                    .padding(vertical = 4.dp),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.spacedBy(8.dp)
                            ) {
                                Box(
                                    modifier = Modifier
                                        .size(18.dp)
                                        .clip(RoundedCornerShape(4.dp))
                                        .background(
                                            if (isChecked) MaterialTheme.colorScheme.primary.copy(alpha = 0.1f)
                                            else Color.Transparent
                                        )
                                        .border(
                                            1.5.dp,
                                            if (isChecked) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurface.copy(alpha = 0.2f),
                                            RoundedCornerShape(4.dp)
                                        ),
                                    contentAlignment = Alignment.Center
                                ) {
                                    if (isChecked) {
                                        Icon(
                                            imageVector = Icons.Default.Check,
                                            contentDescription = null,
                                            tint = MaterialTheme.colorScheme.primary,
                                            modifier = Modifier.size(12.dp)
                                        )
                                    }
                                }

                                Text(
                                    text = task,
                                    style = MaterialTheme.typography.labelMedium,
                                    color = if (isChecked) MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f) else MaterialTheme.colorScheme.onSurface,
                                    fontWeight = if (isChecked) FontWeight.Normal else FontWeight.Medium
                                )
                            }
                        }
                    }
                }
            }
        }
    }
}

// FlowRowLayout utility to support layout constraints gracefully in Compose
@Composable
fun FlowRowLayout(
    spacing: androidx.compose.ui.unit.Dp = 6.dp,
    modifier: Modifier = Modifier,
    content: @Composable () -> Unit
) {
    androidx.compose.ui.layout.Layout(
        content = content,
        modifier = modifier
    ) { measurables, constraints ->
        val xSpacing = spacing.roundToPx()
        val ySpacing = spacing.roundToPx()

        val placeables = measurables.map { it.measure(constraints.copy(minWidth = 0, minHeight = 0)) }
        val layoutRows = mutableListOf<List<androidx.compose.ui.layout.Placeable>>()
        val rowHeights = mutableListOf<Int>()

        var currentRow = mutableListOf<androidx.compose.ui.layout.Placeable>()
        var currentRowWidth = 0
        var currentRowHeight = 0

        placeables.forEach { placeable ->
            if (currentRowWidth + placeable.width > constraints.maxWidth) {
                // Wrap to next row
                layoutRows.add(currentRow)
                rowHeights.add(currentRowHeight)
                currentRow = mutableListOf(placeable)
                currentRowWidth = placeable.width + xSpacing
                currentRowHeight = placeable.height
            } else {
                currentRow.add(placeable)
                currentRowWidth += placeable.width + xSpacing
                currentRowHeight = maxOf(currentRowHeight, placeable.height)
            }
        }
        if (currentRow.isNotEmpty()) {
            layoutRows.add(currentRow)
            rowHeights.add(currentRowHeight)
        }

        val totalHeight = rowHeights.sum() + (rowHeights.size - 1).coerceAtLeast(0) * ySpacing
        layout(constraints.maxWidth, totalHeight) {
            var currentY = 0
            layoutRows.forEachIndexed { rowIndex, row ->
                var currentX = 0
                val rowHeight = rowHeights[rowIndex]
                row.forEach { placeable ->
                    placeable.placeRelative(currentX, currentY + (rowHeight - placeable.height) / 2)
                    currentX += placeable.width + xSpacing
                }
                currentY += rowHeight + ySpacing
            }
        }
    }
}
